prof-ftrace-extractor: \
	$(BLD_PROF)/ftrace-extractor/hpps/prof.hpps-linux.dtb \
	$(BLD_PROF)/ftrace-extractor/hpps/prof.hpps-uboot.dtb

$(BLD_PROF)/ftrace-extractor/qemu/qemu.dts: \
	$(CONF_BASE)/qemu/dt/hpps-ddr-high-1.dts

$(BLD_PROF)/ftrace-extractor/hpps/prof.hpps-uboot.dts: \
	$(CONF_BASE)/hpps/u-boot/dt/hpps-ddr-high-1.dts

$(BLD_PROF)/ftrace-extractor/hpps/prof.hpps-linux.dts: \
	$(CONF_BASE)/hpps/linux/dt/gp-mem.dts

