# Boot RTPS into Bare-Metal App via U-boot and HPPS into Yocto Linux mounted in
# NAND memory, TRCH reads binaries from non-volatile memory.

include $(CONF)/lib-trch-bm/Makefile
include $(CONF)/lib-r52-uboot-bm/Makefile
include $(CONF)/lib-hpps-yocto-nand-rootfs/Makefile
