# Boot HPPS Linux without initramfs: kernel mounts NAND via root= boot arg

include $(CONF)/lib-hpps-linux-nand/Makefile

PROF_CONF=$(CONF)/lib-hpps-linux-nand-rootfs

$(PROF_BLD)/hpps/u-boot.env: $(PROF_CONF)/hpps/u-boot.env
