# Boot Yocto Linux on HPPS from NAND without initramfs (via root= boot arg)

include $(CONF_PROF)/dram-boot/Makefile
include $(CONF_PROF)/hpps-yocto/Makefile
include $(CONF_PROF)/hpps-yocto-nand/Makefile
include $(CONF_PROF)/hpps-linux-nand/Makefile
