# Second-level base config to load RTPS (through boot loader)

prof: rtps/r52/u-boot/u-boot.bin

# Overlays
$(BLD_PROF)/qemu/qemu-env.sh: $(PROF_DIR)/qemu/qemu-env.sh
$(BLD_PROF)/trch/prof.sram.mem.map: $(PROF_DIR)/trch/sram.mem.map
