# Boot TRCH into SSW bare-metal app, have TRCH load boot binaries from
# non-volatile mem into DRAM, boot RTPS R52 into bare-metal app via U-boot,
# boot HPPS into Busybox.

include $(CONF)/platform/Makefile
include $(CONF)/lib-bl0-trch-bm/Makefile
include $(CONF)/lib-r52-uboot-bm/Makefile
include $(CONF)/lib-hpps-busybox/Makefile
