PROF_DIR=$ROOT/bld/prof/$PROF

PROF_QEMU=$PROF_DIR/qemu
QEMU_DT_FILE=$PROF_QEMU/hpsc-arch.dtb
MEMORY_FILES+=($PROF_QEMU/preload.prof.mem.map)

PROF_TRCH=$PROF_DIR/trch
TRCH_SMC_SRAM=$PROF_TRCH/prof.sram.mem.bin
TRCH_SMC_SRAM_OVERWRITE=1

# 0: LSIO 0 (TRCH), 1: LSIO 1 (RTPS R52), 2: HPPS 0 (HPPS)
SERIAL_PORTS_ENABLED[0]=1
SERIAL_PORTS_ENABLED[1]=0
SERIAL_PORTS_ENABLED[2]=0
