# Boot TRCH into bare-metal app, have TRCH load binaries from NV mem (slow),
# and boot HPPS into Busybox on Linux via ATF+U-boot.

include $(CONF)/sys-trch-bm/Makefile
include $(CONF)/lib-trch-bm-nvmem-boot/Makefile
include $(CONF)/lib-hpps-busybox/Makefile
