#!/bin/sh
echo init
echo mount pstore
mkdir -p /pstore
mount -t pstore pstore /pstore

# Location of general-purpose buffer in Linux DT under gpbuf node
# seek = 0x02_0000_0000/4096
dd if=/pstore/ftrace-ramoops-0 of=/dev/mem bs=4096 seek=2097152

exec /bin/sh
