#!/bin/sh
echo init

echo mount tracefs
mount -t tracefs nodev /trace
echo mount debugfs
mount -t debugfs nodev /debug

echo tracer function
echo function > /trace/current_tracer

echo ftrace filters
# Add filters by appending like so:
# echo func_name >> /trace/set_ftrace_filter

echo record ftrace
echo 1 > /debug/pstore/record_ftrace

echo tracer on
echo 1 > /trace/tracing_on

echo exec
exec /bin/sh
