# Boot TRCH into bare-metal app, have TRCH load binaries from NV mem (slow),
# and boot HPPS into Busybox on Linux via ATF+U-boot.

include $(CONF)/platform/Makefile
include $(CONF)/lib-bl0-trch-bm/Makefile
include $(CONF)/lib-hpps-busybox/Makefile
