# Preload BL0 ROM bootloader into TRCH SRAM (by emulator), and have BL0 load
# TRCH SSW bare-metal application (build with minimal features enabled) from
# offchip non-volatile memory, and boot into it.

include $(CONF)/platform/Makefile
include $(CONF)/lib-trch-bm-min/Makefile
include $(CONF)/lib-bl0-trch-bm/Makefile
