# Boot TRCH and run the Rapid IO test

include $(CONF)/trch/Makefile

PROF_CONF=$(CONF)/lib-trch-bm-test-rio

$(PROF_BLD)/qemu/env.sh: $(PROF_CONF)/qemu/env.sh
$(PROF_BLD)/trch/bm.config.mk: $(PROF_CONF)/trch/bm.config.mk
