# Like hps-linux-nand-rootfs, but with boot images preloaded into DRAM by the
# emulator as opposed to being stored in TRCH non-volatile memory.

include $(CONF_PROF)/dram-boot/Makefile
include $(CONF_PROF)/hpps-linux-dram/Makefile
include $(CONF_PROF)/dram-boot-early-initramfs/Makefile

PROF_DIR=$(CONF_PROF)/hpps-linux-nand-rootfs-preload
