OVERLAY=$(CONF)/overlay/hpps-linux-gpmem

prof: $(BLD_PROF)/hpps/linux/hpsc.dtb

$(BLD_PROF)/hpps/linux/hpsc.dts: $(OVERLAY)/linux-gp-mem.dts
$(BLD_PROF)/qemu/preload.prof.mem.map: $(OVERLAY)/qemu/preload.prof.mem.map
$(BLD_PROF)/trch/prof.sram.mem.map: $(OVERLAY)/trch/prof.sram.mem.map
