# Boot Linux on HPPS assuming binaries are preloaded into DRAM

include $(CONF_PROF)/hpps-linux/Makefile

PROF_DIR=$(CONF_PROF)/hpps-linux-preload

$(BLD_PROF)/qemu/preload.prof.mem.map: $(PROF_DIR)/qemu/preload.prof.mem.map
