include $(CONF_PROF)/dram-boot/Makefile
include $(CONF_PROF)/dram-boot-initramfs/Makefile
include $(CONF_PROF)/hpps-booti/Makefile
# include $(CONF_PROF)/hpps-linux-ftrace/Makefile
# include $(CONF_PROF)/hpps-linux-nand-rootfs/Makefile
# include $(CONF_PROF)/hpps-linux-tests/Makefile
