include $(CONF_PROF)/dram-boot/Makefile
include $(CONF_PROF)/hpps-booti/Makefile
include $(CONF_PROF)/hpps-linux/Makefile
include $(CONF_PROF)/hpps-linux-preload/Makefile

# Choose one of the following options (note: not an exhaustive list)
include $(CONF_PROF)/hpps-busybox-initramfs-preload/Makefile
# include $(CONF_PROF)/hpps-yocto-nand-rootfs/Makefile


# include $(CONF_PROF)/hpps-linux-ftrace/Makefile
# include $(CONF_PROF)/hpps-linux-tests/Makefile

include $(CONF_PROF)/rtps-bm/Makefile
include $(CONF_PROF)/rtps-bm-dram/Makefile
