include $(CONF_PROF)/dram-boot/Makefile
include $(CONF_PROF)/dram-boot-early-initramfs/Makefile
include $(CONF_PROF)/hpps-booti/Makefile
include $(CONF_PROF)/hpps-linux/Makefile
include $(CONF_PROF)/hpps-linux-dram/Makefile
include $(CONF_PROF)/rtps-bm/Makefile
# include $(CONF_PROF)/hpps-linux-ftrace/Makefile
# include $(CONF_PROF)/hpps-linux-nand-rootfs/Makefile
# include $(CONF_PROF)/hpps-linux-tests/Makefile
