# [LIB] Boot HPPS Linux via U-boot's booti command

PROF_CONF=$(CONF)/lib-hpps-linux-booti

$(PROF_BLD)/trch/boot.sram.mem.map: $(PROF_CONF)/trch/boot.sram.mem.map
$(PROF_BLD)/hpps/u-boot.env: $(PROF_CONF)/hpps/u-boot.env
$(PROF_BLD)/qemu/preloadable.mem.map: $(PROF_CONF)/qemu/preloadable.mem.map
$(PROF_BLD)/zebu/prof.hpps.dram.mem.map: $(PROF_CONF)/zebu/hpps-mem.map
