# Boot Yocto Linux on HPPS from NAND with initramfs (via switch_root)

SHARE += lib-hpps-yocto-nand

include $(CONF)/lib-hpps-yocto-nand/Makefile
include $(CONF)/lib-hpps-linux-nand-switchroot/Makefile
