# Preload TRCH SSW Bare-Metal App (configured with tests to run on boot) into
# TRCH SRAM (by emulator). Boot TRCH into TRCH SSW BM App, which runs tests.

include $(CONF)/platform/Makefile
include $(CONF)/lib-preload-trch-bm/Makefile
include $(CONF)/lib-trch-bm-preload-boot/Makefile
include $(CONF)/lib-trch-bm-test/Makefile
