# Preload binaries into DRAM by HW emulator (fast), boot TRCH into SSW
# bare-metal app, boot HPPS into Yocto Linux mounted in NAND memory.

include $(CONF)/sys-trch-bm/Makefile
include $(CONF)/lib-trch-bm-dram-boot/Makefile
include $(CONF)/lib-hpps-yocto-nand-rootfs/Makefile
