# Preload TRCH ELF binary into TRCH SRAM (by emulator), and boot into TRCH SSW
# bare-metal application, which then loads system config from NV mem.

include $(CONF)/lib-trch-bm-preload-boot/Makefile
include $(CONF)/lib-trch-bm/Makefile
