# Preload TRCH SSW Bare-Metal App binary (configured with default feature set)
# and syscfg blob into TRCH SRAM (by emulator), and boot into TRCH SSW
# Bare-Metal App.

include $(CONF)/platform/Makefile
include $(CONF)/lib-trch-bm/Makefile
include $(CONF)/lib-trch-bm-preload-boot/Makefile
include $(CONF)/lib-preload-trch-bm/Makefile
include $(CONF)/lib-trch-bm-default/Makefile
