# Preload TRCH BM app ELF binary and syscfg blob into TRCH SRAM (by emulator),
# and boot into TRCH SSW bare-metal application.

include $(CONF)/platform/Makefile
include $(CONF)/lib-trch-bm/Makefile
include $(CONF)/lib-trch-bm-preload-boot/Makefile
include $(CONF)/lib-preload-trch-bm/Makefile
