prof: $(BLD_PROF)/hpps/linux/early.initramfs.uimg

PROF_DIR=$(CONF_PROF)/hpps-linux-early-initramfs

$(BLD_PROF)/trch/prof.sram.mem.map: $(PROF_DIR)/trch/sram.mem.map
$(BLD_PROF)/hpps/u-boot/uboot.env: $(PROF_DIR)/hpps/u-boot/uboot.env
