CONFIG_SYSTICK                  = 1
CONFIG_SLEEP_TIMER              = 1 # implement sleep() using a timer
CONFIG_SYSCFG                   = 1
CONFIG_HPPS_TRCH_MAILBOX        = 0
CONFIG_HPPS_TRCH_MAILBOX_ATF    = 0
CONFIG_HPPS_TRCH_MAILBOX_SSW    = 0
CONFIG_RTPS_TRCH_MAILBOX        = 0
CONFIG_RTPS_TRCH_MAILBOX_PSCI   = 0
CONFIG_RTPS_TRCH_SHMEM          = 0
CONFIG_HPPS_TRCH_SHMEM          = 0
CONFIG_HPPS_TRCH_SHMEM_SSW      = 0
CONFIG_TRCH_WDT                 = 0
CONFIG_RTPS_R52_WDT             = 0
CONFIG_RTPS_A53_WDT             = 0
CONFIG_HPPS_WDT                 = 0
CONFIG_TRCH_DMA                 = 0
CONFIG_RT_MMU                   = 0 # RTPS/TRCH->HPPS MMU
CONFIG_SMC			= 0
CONFIG_SFS			= 0
