PROF_DIR=$(CONF_PROF)/hpps-ddr-high

prof: $(BLD_PROF)/hpps/u-boot/hpsc-hpps.dtb

$(BLD_PROF)/qemu/hpsc-arch.dts: $(PROF_DIR)/hpps-ddr-high-1.qemu.dts
$(BLD_PROF)/qemu/preload.prof.mem.map: $(PROF_DIR)/qemu/preload.prof.mem.map
$(BLD_PROF)/hpps/u-boot/hpsc-hpps.dts: $(PROF_DIR)/hpps-ddr-high-1.uboot.dts
$(BLD_PROF)/trch/prof.sram.mem.map: $(PROF_DIR)/trch/prof.sram.mem.map
