PROF_DIR=$(CONF_PROF)/hpps-booti

$(BLD_PROF)/hpps/u-boot/uboot.env: $(PROF_DIR)/hpps/u-boot/uboot.env
$(BLD_PROF)/qemu/preload.prof.mem.map: $(PROF_DIR)/qemu/preload.prof.mem.map
$(BLD_PROF)/zebu/prof.hpps.mem.map: $(PROF_DIR)/zebu/hpps-mem.map
