# Like hpps-yocto-nand-rootfs but with boot images preloaded into DRAM memory
# by the emulator.

include $(CONF_PROF)/hpps-yocto-nand-rootfs/Makefile
include $(CONF_PROF)/dram-boot/Makefile
include $(CONF_PROF)/hpps-linux-preload/Makefile
