# Enable the execution speed workaround using SVE instruction in ATF

$(call push-prof)
# includes
PROF_CONF:=$(CONF)/$(call pop-prof)

$(PROF_BLD)/hpps/atf.config.mk: $(PROF_CONF)/hpps/atf.config.mk
