# Preload binaries into DRAM by HW emulator (fast), boot RTPS into SSW
# bare-metal App via U-boot, boot HPPS into Yocto Linux mounted in NAND memory.

include $(CONF)/platform/Makefile
include $(CONF)/lib-trch-bm-preload-boot/Makefile
include $(CONF)/lib-trch-bm/Makefile
include $(CONF)/lib-r52-uboot-bm/Makefile
include $(CONF)/lib-hpps-yocto-nand-rootfs/Makefile
