# Boot TRCH and run the Rapid IO test

include $(CONF_PROF)/trch/Makefile

PROF_DIR=$(CONF_PROF)/trch-test-rio

$(BLD_PROF)/qemu/env.sh: $(PROF_DIR)/qemu/env.sh
$(BLD_PROF)/trch/bm.config.mk: $(PROF_DIR)/trch/bm.config.mk
