# Preload image of TRCH SSW bare-metal application into TRCH on-chip SRAM and
# preload RTPS R52 Bare Metal application to RTPS DRAM, boot TRCH and have it
# boot RTPS R52 into SSW bare-metal application via U-boot.

include $(CONF)/platform/Makefile
include $(CONF)/lib-preload-trch-bm/Makefile
include $(CONF)/lib-trch-bm-preload-boot/Makefile
include $(CONF)/lib-r52-uboot-bm/Makefile
