# Preload TRCH SSW bare metal application image into TRCH onchip SRAM (by
# emulator), boot TRCH and have TRCH load binaries from non-volatile memory and
# boot RTPS R52 into SSW bare-metal application via U-boot.

include $(CONF)/platform/Makefile
include $(CONF)/lib-bl0-trch-bm/Makefile
include $(CONF)/lib-r52-uboot-bm/Makefile
