include $(CONF_PROF)/dram-boot/Makefile
include $(CONF_PROF)/trch-minimal/Makefile
include $(CONF_PROF)/rtps-minimal/Makefile
include $(CONF_PROF)/hpps-booti/Makefile
# include $(CONF_PROF)/hpps-linux-tests/Makefile
