TEST_FLOAT 				= 1
TEST_SYSTICK			= 1
TEST_WDTS 				= 1
TEST_TRCH_DMA			= 1
TEST_TRCH_DMA_CB 		= 1 # if set, use callback, otherwise call dma_wait
TEST_RT_MMU				= 1
TEST_ETIMER				= 1
TEST_RTI_TIMER			= 1
TEST_SHMEM				= 1
