include $(CONF_PROF)/hpps-linux/Makefile

prof: $(BLD_PROF)/hpps/linux/yocto/conf/local.conf \
      $(BLD_PROF)/hpps/linux/yocto/conf/bblayers.conf

PROF_DIR=$(CONF_PROF)/hpps-linux-yocto

$(BLD_PROF)/qemu/qemu-env.sh: $(PROF_DIR)/qemu/qemu-env.sh
