# Configure RTPS R52 core 1 reset vector for SSW BM RTPS R52 app.

$(call push-prof)
# includes
PROF_CONF:=$(CONF)/$(call pop-prof)

# TODO: RVBAR should be dynamically settable via TRCH
$(PROF_BLD)/qemu/hpsc.dts: $(PROF_CONF)/qemu/hpsc.dts
