PROF_DIR=$(CONF_PROF)/hpps-linux-gpmem

prof: $(BLD_PROF)/hpps/linux/hpsc.dtb

$(BLD_PROF)/hpps/linux/hpsc.dts: $(PROF_DIR)/linux-gp-mem.dts
$(BLD_PROF)/qemu/preload.prof.mem.map: $(PROF_DIR)/qemu/preload.prof.mem.map
$(BLD_PROF)/trch/prof.sram.mem.map: $(PROF_DIR)/trch/prof.sram.mem.map
