# Add general-purpose reserved memory buffer for I/O into the machine.

$(call push-prof)
# includes
PROF_CONF:=$(CONF)/$(call pop-prof)

$(PROF_BLD)/hpps/linux/hpsc.dts: $(PROF_CONF)/linux-gp-mem.dts
