OVERLAY=$(CONF)/overlay/hpps-booti

$(BLD_PROF)/$(PROF)/hpps/u-boot/uboot.env: $(OVERLAY)/hpps/u-boot/uboot.env
$(BLD_PROF)/$(PROF)/qemu/preload.mem.map: $(OVERLAY)/qemu/preload.mem.map
$(BLD_PROF)/$(PROF)/zebu/prof.hpps.mem.map: $(OVERLAY)/zebu/hpps-mem.map
