# Like hpps-yocto-initramfs, but with boot images preloaded into DRAM by the
# emulator as opposed to being stored in TRCH non-volatile memory.

include $(CONF_PROF)/dram-boot/Makefile
include $(CONF_PROF)/hpps-linux-preload/Makefile
include $(CONF_PROF)/hpps-yocto-initramfs/Makefile
include $(CONF_PROF)/hpps-linux-initramfs-preload/Makefile
