# Preload binaries into DRAM by HW emulator (fast), boot TRCH into bare-metal
# app, boot HPPS into Busybox on Linux via U-boot+ATF.

include $(CONF)/platform/Makefile
include $(CONF)/lib-trch-bm-preload-boot/Makefile
include $(CONF)/lib-trch-bm/Makefile
include $(CONF)/lib-hpps-busybox/Makefile
