# Preload TRCH ELF binary and system config blob into TRCH SRAM (by emulator),
# and boot into TRCH SSW bare-metal application.

include $(CONF)/lib-trch-bm-nvmem-boot/Makefile
include $(CONF)/lib-trch-bm/Makefile
