# Boot Yocto Linux on HPPS from NAND with initramfs (via switch_root)

include $(CONF_PROF)/dram-boot/Makefile
include $(CONF_PROF)/hpps-yocto/Makefile
include $(CONF_PROF)/hpps-yocto-nand/Makefile
include $(CONF_PROF)/hpps-linux-nand-switchroot/Makefile
