# Boot TRCH with the SSW baremetal application with test suite executed on
# boot; boot RTPS R52 into SSW bare-metal application with test suite executed
# on boot.

include $(CONF)/sys-trch-bm/Makefile
#include $(CONF)/lib-trch-bm-dram-boot/Makefile # preloaded works too
include $(CONF)/lib-trch-bm-nvmem-boot/Makefile
include $(CONF)/lib-trch-bm-test/Makefile
include $(CONF)/lib-r52-uboot-bm/Makefile
include $(CONF)/lib-r52-bm-test/Makefile
